stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."
    - 
    - docker build -t my-app .

test:
  stage: test
  script:
    - echo "Running tests..."
    - echo "Running rabbitmq"
    - docker pull rabbitmq:management
    - docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:management
    - echo "Running JwtAuthService"
    - docker build -t your-auth-service JwtAuthService/
    - docker run -d -p 5146:5146 --name auth-service-container your-auth-service
    - echo "Running ProtectedService"
    - cd ProtectedService
    - docker build -t protected-service -f ProtectedService/Dockerfile .
    - docker run -d -p 5147:5147 --name protected-service-container protected-service

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - docker push my-app
