@JwtAuthService_HostAddress = http://localhost:5146

POST {{JwtAuthService_HostAddress}}/auth/register/
Accept: application/json
Content-Type: application/json

{
"Username" : "Mike",
"Password" : "123"
}

###
POST {{JwtAuthService_HostAddress}}/auth/login/
Accept: application/json
Content-Type: application/json

{
  "Username" : "Mike",
  "Password" : "123"
}